### ISSUE TITLE
Cannot get the gradle (groovy) releaseTypes definition to override the defaults for preset 'extended'

### ISSUE THREAD

**Issue by boardbloke** [mooltiverse/nyx#118]
I was following the examples documented at

https://levelup.gitconnected.com/semantic-release-automation-with-gradle-using-nyx-ba345235a365

And using version 1.2.2

And trying to override the collapsedVersionQualifier for the feature branch thus:
```
nyx {
    // See https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/
    preset = 'extended'

    releasePrefix = 'build-'

    changelog {
        path = 'build/CHANGELOG.md'
    }

    releaseTypes {
        items {
            feature {
                collapsedVersionQualifier = '{{#sanitizeLower}}TEST{{/sanitizeLower}}'
            }
        }
    }
}
```

But it seems to override the feature config as when I do nyxInfer I get "build-1.0.1', when I expected "build-1.0.1-test.1".  If I comment out the releaseTypes config I get "build-1.0.1-featuredbtech1235exampletext.1", which is what I expected.

So I'm wondering adding any config in the releaseTypes section causes the "extended" config to be ignored, and the article is incorrect, or there is an issue here?

The rationale for this is that I ideally want to be able to have feature branches that look like "feature/[jira-id]_some_helpful_text", e.g. "feature/ABCD-1234_fix_breaking_widget" but have that turn into a version that looks like either "build-1.0.1-feature_ABCD1234" or "build-1.0.1-ABCD1234"

It seems That's not currently possible at the moment because I think would require some template functions that can:
  strip git directories (i.e. trim leading characters in the branch name up to the final /)
  strip trailing characters after a leading regex defined by config (so I could define a regex for jira is as [a-A-Z]*-[0-9]* to identify the prefix to keep) - and then sanitize that to get an identifier friendly enough to use in a version suffix.

**Comment by flelli** [comment]
Hi @boardbloke,

it's true that configurations can be extended and their values can be overridden but when it comes to complex objects like `releaseTypes` they must be redefined as a whole. I see this is not clear from the docs and I will update it soon ( #121 ).

This means that your configuration needs to redefine the whole `feature` release type or it will be interpreted as a release type that uses all default values but the `collapsedVersionQualifier`.

In other words your configuration should look like:

```
nyx {
    // See https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/
    preset = 'extended'

    releasePrefix = 'build-'

    changelog {
        path = 'build/CHANGELOG.md'
    }

    releaseTypes {
        items {
            feature {
                collapseVersions = true
                collapsedVersionQualifier = '{{#sanitizeLower}}TEST{{/sanitizeLower}}'
                description = 'Feature release {{version}}'
                filterTags = '^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(feat|feature)(([0-9a-zA-Z]*)(\\.([0-9]\\d*))?)?)$'
                gitCommit = 'false'
                gitPush = 'false'
                gitTag = 'false'
                matchBranches = '^(feat|feature)((-|\\/)[0-9a-zA-Z-_]+)?$'
                publish = 'false'
                versionRangeFromBranchName = false
            }
        }
    }
}
```

Here I just copied the `feature` release type definition from the `extended` preset, replacing the `collapsedVersionQualifier` with your value. I believe this behaves as you expected.

With a little more detail, you get `build-1.0.1` instead of `build-1.0.1-test.1` because the default value for `collapseVersions` is `false` so the `collapsedVersionQualifier` is not even used.

I think the use case you mentioned can be implemented by changing the above configuration according to your needs, using regular expressions and functions.

I'm closing this issue but feel free to reopen or add comments if needed.
