### ISSUE TITLE
replace the '+' in the version to other symbol

### ISSUE THREAD

**Issue by AnakinPt** [mooltiverse/nyx#180]
When I'm using the nyx, let's say I have a branch "feature/foo" with a commit "feat: System supports foo".

With this configuration, if I add identifiers to the internal block, it will separate the build to the pre_release using a '+' sign. This is a problem, because I can't use the version directly in the docker image tag because I can't have a + sign. Can I change this '+' by something else in nyx or I need to sanitize it in the docker image?

nyx {
    dryRun = false
    preset = 'simple'
    releaseLenient = true
    releasePrefix = 'v'
    scheme = "SEMVER"
    verbosity = "WARNING"
    releaseTypes {
        publicationServices = ['gitlab']
        enabled = ['mainline', 'internal']
        items {
            mainline {
                collapseVersions = false
                filterTags = '^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$'
                gitCommit = 'false'
                gitCommitMessage = 'Release version '
                gitPush = 'true'
                gitTag = 'true'
                gitTagMessage = 'Tag version '
                matchBranches = '^(master|main)$'
                matchEnvironmentVariables {
                    CI = '^true$'
                }
                matchWorkspaceStatus = 'CLEAN'
                publish = 'true'
                versionRangeFromBranchName = false
            }
            internal {
                collapseVersions = true
                collapsedVersionQualifier = '{{#sanitize}}{{branch}}{{/sanitize}}'
                description = 'Internal release '
                gitCommit = 'false'
                gitPush = 'false'
                gitTag = 'false'
                publish = 'false'
                versionRangeFromBranchName = false
            }
        }
    }
    services {
        gitlab {
            type = "GITLAB"
            options {
                REPOSITORY_NAME = <myRepo>
                REPOSITORY_OWNER = <myOwner>
            }
        }
    }
}

**Comment by flelli** [comment]
Hi @AnakinPt ,

I can't see any [`identifiers`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#identifiers) block in the above configuration but I guess your test had it.

You can set the [identifier position](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#identifier-position) to `PRE_RELEASE` to have your identifier prefixed by a `-`, otherwise the default `BUILD` will use the `+`. By using the `PRE_RELEASE` position the extra identifier is added to the [pre-release part](https://semver.org/), otherwise it goes in the https://semver.org/.

The other option, as you said, is to sanitize the verion with something like:

```
sanitizedVersion = rootProject.version.replaceAll('\\+','_')
```

**Comment by AnakinPt** [comment]
That was what I had to do. I use version per commits and that + sign doesn't allow me to create a simple version while we don't merge.

**Comment by flelli** [comment]
Have you tried the `PRE_RELEASE` setting above?
