### ISSUE TITLE
Merge/rebase PR from collapsed version branch to release branch does not infer new version

### ISSUE THREAD

**Issue by sfat** [mooltiverse/nyx#185]
Hi, been playing recently with your plugin (nice work 🎉 ) to try to integrate it, but I found a strange behaviour which I'm not sure if it's a bug or not:

https://github.com/sfat/release-gradle-plugins-playground

I have 2 branches configured:
* `main` - this is my integration branch where I would want to have collapsed versions suffixed with `alpha`
* `prod` - this is where I want my releases

When I create a PR to merge things from my `main` branch to `prod`, whenever I check to merge my PR with either merge or rebase, for some reason, on my `prod` branch, nyx does not infer the version correctly. Obviously, I don't want to squash my commits from `main` to `prod`, so I haven't tested that scenario.

I did read your article regarding [how nyx handles merge commits](https://mooltiverse.github.io/nyx/faq/user/how-does-nyx-deal-with-merge-commits-when-scanning-the-commit-history/), but I think it does not actually pick the correct parent commit, resulting in remaining in my previous prime version.

If I do a rebase commit, since GitHub does not have a proper rebase with fast forward way of merging [PRs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github#rebasing-and-merging-your-commits), in this scenario nyx, since `prod` now has X commits ahead and X commits behind `main`, now on `main`, nyx doesn't see the latest prime version, but a previous version, which makes the collapsed versions keep incrementing previously released version (see https://github.com/sfat/release-gradle-plugins-playground/actions/runs/4441247886/jobs/7796087142, here `3.6.0` is already released, but it still sees `3.5.1` as the prime version, I think eventually if I don't force a major bump or something, when merging into `prod`, nyx will fail because it will try to retag a previous git tag - `3.6.0` in this case).

The only way I can overcome this issue is to not use GitHub PRs and just perform a `git rebase main` on my `prod` locally and do a push, but I'm wondering is this a bug or am I not understanding how this plugin should work.

**Comment by flelli** [comment]
Hi @sfat ,

I'm not sure I got it all right but here's my guesses. You tell me if there's anything wrong in my assumptions.

The [pipeline you linked](https://github.com/sfat/release-gradle-plugins-playground/actions/runs/4441247886/jobs/7796087142) seems correct because the tag `3.6.0` is on the `prod` `HEAD` but it's still not _visible_ from `main` (where the pipeline runs) therefore the previous version `3.6.0-alpha.2` is correctly inferred from c7828b0 and so is the prime version `3.5.1` from `19f6115` as they are both in the `main` _visible_ commit history.

![Untitled](https://user-images.githubusercontent.com/23358646/225837237-0a2dc4ae-4a65-4e81-a165-14ed3c628502.jpg)

Consider that Nyx cannot span over the entire repository but can only start from the latest commit and go backward, following only the first parent commit in case of multiple parents.

When merging between two long running branches [the first parent commit is the one the branch comes from](https://mooltiverse.github.io/nyx/faq/user/concepts/whats-the-difference-between-the-prime-version-and-the-previous-version/), not the one of the incoming merge, and this is part of Git's core behavior.

In general, I suggest you not to tag **core** versions from multiple branches right because of the issue you have foreseen (tags clashing).

**Comment by sfat** [comment]
Yeah, I tested also with https://github.com/semantic-release/semantic-release, just to prove myself is not the plugin itself and you are right, it's basically Git itself acting like that when it comes to multiple long lived branches 

Thanks for the explanation!

**Comment by flelli** [comment]
You're welcome @sfat !
