### ISSUE TITLE
The releaseType resolves to internal even when on main branch + more config questions

### ISSUE THREAD

**Issue by javaworkinggirl** [mooltiverse/nyx#189]
Hi.  I 'm using gradle 8.0.2 and gradle kotlin dsl with Gitlab and nyxInfer seems to be always resolving releaseType to **internal** even when I am on the main branch.  This is what I got on Gitlab on main from my last build:

`
Project version: 0.2.0-internal.1+e2fff42ca3f74685847ca41a7a1c5f09e9d7f5cc
> Task :nyxPublish
Publish release: 0.2.0-internal.1+e2fff42ca3f74685847ca41a7a1c5f09e9d7f5cc
> Task :release
`

Also, we need a really simplified gitmoji scheme.  We want to always increment the patch version when merging a branch into main.  So any commit will do as long as no :boom: or :sparkles: .  We will reserve those for major and minor, respectively.   Is how my config is set up the way to go, or is there better configuration to accomplish this?

So far my code has not connected to gitlab either.  It doesn't seem to publish or release anything.  I am doing this in .gitlab-ci.yml:
`    - gradle release
`

Possibly I don't need the git stanza of .nyx.yml because gitCommit is set to false in my config?  gitCommit=true pushes the changelog? Is that correct?

Also does this plugin need all the git tags to calculate the version, or will the last 20 tags be enough?

Thanks and what insights do you have?

I attached my .nyx.yml
[nyx.yml.txt](https://github.com/mooltiverse/nyx/files/11085267/nyx.yml.txt)

**Comment by flelli** [comment]
Hi @javaworkinggirl ,

I'd need the debug output to see why it always falls back to the `internal` or you can inspect it yourself, knowing that most of the times it's because the repo is not CLEAN, which means it has uncommitted changes. If that's the point you can override the `mainline` configuration and set the [`matchWorkspaceStatus`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#match-workspace-status) to empty, or create a new release type that batter suits your needs.

It's hard to tell if your gitmoji configuration works, that depends on your needs. What I can recommend is to use tools like [this ](https://regex101.com/) to check your regular expressions against test commit messages.

The Git configuration is indeed only needed when you push contents to the remote repo, so if you don't you can skip that configuration.

For the number of tags, 20 are probably enough, as long as the latest _previous_ and _prime_ version are among those 20. My suggestion is to check out the entire repository, unless it's so big to slow down the pipeline.
