### ISSUE TITLE
unable to configure the Collapsed version qualifier

### ISSUE THREAD

**Issue by lxke19** [mooltiverse/nyx#204]
Hey @flelli could somebody pls help us configure the Collapsed version qualifier.

Everytime we commit on a branch which isn't the main branch, we want i to be an alpha version number. For Example if i create a feature branch the version schould come out as an "alpha"-version : "1.2.4-alpha". But we are unable to find the right configuration, is this even possible? We found this in the Documentation( https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#collapsed-version-qualifier ). 

thanks in advance

**Comment by flelli** [comment]
Hi @lxke19 ,

I'm assuming `alpha-version` is a typo, instead of `version-alpha`. The core version must appear first, otherwise it's not supported by Nyx because it wouldn't be Semver compliant.

You already got to the right configuration option. Probably you miss the [release type](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/) configuration, where you match the branch names (using regular expressions).

You can use the [extended preset](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/) or take it as an example (look at the _maturity_ release type). Otherwise you can take a look at [this example](https://mooltiverse.github.io/nyx/example/user/extended-configuration-example/)
