### ISSUE TITLE
How can we disable nyx in gradle build

### ISSUE THREAD

**Issue by lxke19** [mooltiverse/nyx#213]
Hey @flelli ,

we would like to start the nyx Tasks on our own. How can we disable them, so they dont start during gradle build? (nyxMake, nyxMark)

is it possible to exclude nyxMake or disable the changelog?

and how can we define a default line for releaseTypes? We tryed it with "matchBranches.set("null")" but now it says: No suitable release types have been configured or none of the configured release types matches the current environment

Here is our configuration:

releaseTypes {
        enabled.set(
            listOf(
                "mainline", "feature"
            )
        )
        items {
            create("mainline") {
                collapseVersions.set(false)
                gitCommit.set("true")
                gitCommitMessage.set("Release version")
                gitPush.set("true")
                gitTag.set("true")
                gitTagMessage.set("Tag version")
                matchBranches.set("master|main")
                versionRangeFromBranchName.set(false)
                publish.set("true")
            }

            create("feature") {
                collapseVersions.set(true)
                collapsedVersionQualifier.set("alpha")
                description.set("Feature Release")
                gitCommit.set("true")
                gitPush.set("true")
                gitTag.set("true")
                matchBranches.set("null")
                publish.set("true")
                versionRangeFromBranchName.set(false)
            }
        }
    }

Thanks in advance, 

Luke

**Comment by flelli** [comment]
Hi @lxke19 ,

in order to run tasks explicitly you just need to [apply the plugin](https://skylltech.atlassian.net/wiki/spaces/OCM/pages/edit-v2/360659) as a regular project plugin in the `build.gradle` file instead of `settings.gradle` (which makes it a settings plugin and start it as soon as the build starts).

For the default release type you need a catch-all release type (what is called _internal_ in examples like [this](https://mooltiverse.github.io/nyx/example/user/extended-configuration-example/)) and [enable](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#enabled) it as the last one so that it's only matched if no other more specific release type is matched first. In this release type you can omit all the `catch*` attributes.
