### ISSUE TITLE
Remove changelog from extended preset

### ISSUE THREAD

**Issue by lxke19** [mooltiverse/nyx#214]
Hey @flelli,

I'm trying to remove the changelog from nyx, it should work if I remove the extended preset and use the simple one instead. But without the extended preset my configuration doesen't work. What could I do instead of using the simple preset.

Thanks in advance

Lukas

**Comment by flelli** [comment]
@lxke19 , you can just set the changelog [path](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/changelog/#path) to the empty string.

Otherwise you can start from the simple preset or an empty configuration and add the configurations you need. Maybe in this case you can grab the current configuration from the [state](https://mooltiverse.github.io/nyx/guide/user/state-reference/global-attributes/#configuration) and integrate the chunks you need into the new configuration to save time.
