### ISSUE TITLE
`nyx mark` results in `author field is required` error

### ISSUE THREAD

**Issue by rrzal** [mooltiverse/nyx#216]
I already configured `git` and `services`:
```json
"git": {
        "remotes": {
            "origin": {
                "authenticationMethod": "USER_PASSWORD",
                "user": "PRIVATE-TOKEN",
                "password": "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}"
            }
        }
    },
"services": {
        "gitlab": {
            "type": "GITLAB",
            "options": {
                "BASE_URI": "my gitlab instance",
                "AUTHENTICATION_TOKEN": "{{#environmentVariable}}GITLAB_TOKEN{{/environmentVariable}}",
                "REPOSITORY_NAME": "my-repo",
                "REPOSITORY_OWNER": "me"
            }
        }
    },
```

However, when nyx tried to commit changes, I get:
```console
time="2023-05-16T14:45:06-07:00" level=debug msg="workaround #130: the 'git status' command returned (empty means the repository is clean): '?? version.h\n'"
time="2023-05-16T14:45:06-07:00" level=debug msg="workaround #130: the 'git status' command returned a non-empty output so the repository is dirty"
time="2023-05-16T14:45:06-07:00" level=debug msg="committing local changes"
time="2023-05-16T14:45:06-07:00" level=debug msg="the configured commit message template yields to an empty commit message. Using default template 'Release version {{version}}'"
time="2023-05-16T14:45:06-07:00" level=debug msg="adding contents to repository staging area"
time="2023-05-16T14:45:06-07:00" level=debug msg="committing changes to repository"
an error occurred when trying to commit: author field is required
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit status 1
```

job config:
```yml
release-job:
  stage: release
  tags:
    - shell
  script:
    - git checkout -b $CI_COMMIT_BRANCH
    - nyx mark
```

**Comment by flelli** [comment]
> I fixed this issue by setting `git config` before `mark`
> 
> ```yaml
>     - git config user.name "Linux CI Station"
>     - git config user.email "you@example.com"
>     - nyx mark
> ```
> 
> Maybe nyx config should include the git author config to make it more streamlined? Or maybe I'm just not using it correctly. Let me know

That's the correct behavior. Git takes the author from its own config. Maybe it's worth to point this out in the docs

**Comment by flelli** [comment]
> Hi @flelli, I just realized by using `nyx mark`, it's ignoring `.gitignore` and adding everything in the workspace to the commit, like `nyx-state` and `nyx-summary`. Is it intended behavior?
> 
> To clarify, my intended use case is: I have a integration branch called `development`, every time I merge a feature/fix into it, I want to run a custom script to generate a new version file, update a python package version, etc. After that, I use `nyx mark` to commit these new files/changes to my branch. Not sure if it's the correct workflow/intended use case, and why it is ignoring `.gitignore`

Nyx must comply with `.gitignore`, if it doesn't it's a bug. Actually this is up to the [library](https://pkg.go.dev/github.com/go-git/go-git/v5) Nyx uses internally.
Your use case has nothing wrong from Git's and Nyx' point of view.
Do you have a repo I can reproduce the issue in?

**Comment by flelli** [comment]
Hi @rrzal ,

for this last case I need to see the logs and the state output, otherwise I can't help.

For the first part the behavior is correct because:

- the previous version is `v0.1.0` and is correctly detected
- the release scope (the commits determining the new version) tell that both the `patch` and the `minor` identifier must be bumped
- when more identifiers are to be bumped, only the most significant (`patch` in this case) is actually bumped, while the less significant are reset to their default (so `minor` is reset to 0)
- the pre-release identifier (after `featnoneaddnyxconfig`) is less significant than any other core identifier, so it's also reset to 1 (collapsed identifiers start from 1 instead of 0)

This is by design, otherwise you may have sequences like 0.1.0, 0.1.1, 0.2.2 (missing versions between 0.1.1 and 0.2.2), which would be inconsistent.

If you want all versions tagged in between you need to run Nyx at each significant commit, so it tags each single version.

I hope this clarification helps for your merge commits as well.

**Comment by flelli** [comment]
Hi @rrzal ,

> From what you explained, if I understand it correctly now, Nyx actually works in this way:
> 
> * Find the most recent tag, which is `v0.1.0`
> * Then after going through all commit messages, Nyx determines that minor, patch, and prerelease versions need to be bumped (it doesn't matter how many times they need to be bumped)
> * Since minor version takes precedence, Nyx only bumps the minor version, and initializes the prerelease version, which results in
>   `v0.2.0-featnoneaddnyxconfig.1`
> 
> So, in order for it to work as the way I described, I need to use `nyx mark` to tag the branch after every commit I make.

Correct. It's up to you to tag each version by running Nyx at each commit or make it shrink releases by running it cumulatively after a batch of commits.

> For my second case, I think the problem was I didn't use conventional commit message in my merge request title. After setting the merge request title to be `fix: xxx` or `feat: xxx`, Nyx seems to correctly tag my development branch and create a new release after ever merge. However, this leads to another confusion: From what I observed, Nyx only uses the merge request title to determine the next version of the target branch, and nothing else. So, the ONLY thing that determines the next version after a merge is the merge request title, is it correct? For example:
> 
> * I have a `development` branch and a `master` branch. I've merged a feature branch and a fix branch into the `development` branch. Now, I have `v0.1.0`, `v0.2.0`, and `v0.2.1` in my repo.
> * I created a merge request to merge my `development` branch into my `master` branch.
> * If I don't use conventional commit message in my merge request title, Nyx will not bump the version of `master` at all. After the merge, `master` remains `v0.1.0`
> 
> * On the other hand, if I use `release!: new version` as my merge request title, Nyx successfully creates a new release:

Correct. Remember that a merge commit, from Nyx, is just a commit like any other and so its message etc are parsed to compute versions.
Nyx ha no concept of pull/merge request, which is specific to GitHub, GitLab etc. Nyx only reads the repository.
The only difference between a _regular_ commit and a _merge_ commit for Nyx is that a [merge commit has multiple (usually 2) parent commits instead of just one](https://mooltiverse.github.io/nyx/faq/user/how-does-nyx-deal-with-merge-commits-when-scanning-the-commit-history/).
