### ISSUE TITLE
What's the purpose of `matchWorkspaceStatus` and how should it be utilized?

### ISSUE THREAD

**Issue by rrzal** [mooltiverse/nyx#227]
I understand what it does, but I don't know utilize this option.

The way I understand `nyx mark` is that it should be called as the final step in the pipeline and it commits any modifications made to the repository during the pipeline, so, a `DIRTY` workspace status is required for it to work. However, I'm unsure of the use case where a CLEAN workspace status would be appropriate for a release type.

**Comment by flelli** [comment]
Hi @rrzal ,

not all pipelines create new artifacts to commit. Requiring the `CLEAN` status is helpful, for example, when you want to make sure there is no pending change (likely because you want to make sure that all CI/CD tests have run before releasing).

In your case, as far as I understand, the `DIRTY` state is not **required**, but is allowed. In other words you shoudn't set that attribute for the specific release type otherwise the release type is not matched if the status is `CLEAN`.
