### ISSUE TITLE
How to "inherit" version from another branch when merge?

### ISSUE THREAD

**Issue by rrzal** [mooltiverse/nyx#228]
The documentation says Nyx only follows the first parent for merge, so any version info in the incoming branch is ignored.
In this case, is it possible to achieve the following:

I have a integration branch `development`. The version number is not collapsed. I have `gitTag`, `gitCommit`, and `gitPush` enabled. but it does not create new releases (`publish` is set to `false`).

I use my `master` branch as a release branch. So every time I merge `development` into `master`, I just want to keep the latest version from `development` as is, and run publish using said version. I don't need to increment the version on my `master` branch.

I can configure the pipeline to run the publish job in `master` every time. The problem is, my build scripts, publish scripts, etc. may use the version number inferred by Nyx (which I save as environment variables), But because Nyx cannot get the version number from `development` branch, `current_version`, `previous_version`, etc. are all wrong. I also cannot utilize the `newRelease` and `newPublish` flags or the built-in `publish` feature. 

I have figured out some hacky way to do it, such as having `master` skip nyx workflow completely and parse the version from my setup.py etc., but it doesn't feel right.

 Is there a way to circumvent this issue or any suggestions for handling this kind of scenarios?

**Comment by paulhirst-cb** [comment]
I would also love an answer to this. I'm doing gitflow, so I have a develop branch from main which feature branches are taken from and then merged back into develop. When appropriate develop is merged into main.

Unless I specifically add commits to main to bump the version number, it never changes, as all the commits made in the feature branches (or directly in develop) are ignored when it comes to calculating the version number for main.

I first tested Nyx by committing directly into main and of course everything worked great. Is there a way to consider the history on _both_ sides of a merge?

I'm questioning my own sanity a bit because surely all but the smallest of projects work like this? I fear I'm just misunderstanding something fundamental here.

**Comment by flelli** [comment]
Hi @rrzal and @paulhirst-cb ,

the short answer is the use case is not supported.

Here's a little explanation.

First, Nyx only tags and publishes the current commit, not past ones, which are supposed to be handled by previous runs. Altering previous commits would soon lead to inconsistencies (suppose you bump a version on a previous commit, which makes it greater than the commits coming afterwards, or bumping a commit from a parent branch that would later on conflich with a commit from another parent).

Second, considering two parent commits would potentially mean considering any number of parent commits (consider so called *octopus merges*, allowed by Git). This would make it impossible for Nyx to determine which versions to start from as previous or prime commit.

Third, many use cases run different checks or pipelines to validate a tag before it's applied and published, and this is often conditional to the branch. `master` is likely to run complete checks (more tests and gates) than other branches (i.e. `develop`) so in this case we'd allow an _official_ release to be merged into `master` with only shallow tests performed in _develop_.

My bit of advice here is that you should tag and publish a release on a certain commit consistently with the branch where the commit lives at the time of Nyx runs, otherwise you'd soon encounter inconsistencies.

If you really want to go down that way you can:

1. match the `develop` branch along with `main` in the same release type so that your official release is published when the commit is still in `develop`. Then merge into `main` without squashing so that the commit will stay in the history. In this case you may encounter version conflicts in the `main` branch if you merge from other branches as well or you accidentally squash a merge
2. do the tagging and publishing only in the `develop` branch by configuring its own release type and do not do the same in `main`
