### ISSUE TITLE
Accessing current date or time in release name

### ISSUE THREAD

**Issue by ennioVisco** [mooltiverse/nyx#260]
`"releaseName": "{{version}} ({{#timeFormat format=\"yyyyMMdd\"}}{{/timeFormat}})"` or `"releaseName": "{{version}} ({{#timeFormat format=\"yyyyMMdd\"}} {{timestamp}} {{/timeFormat}})"` are returning the format string, like there is no `{{timestamp}}`, while `{{version}}` is correct, in `.nyx.json`, section `releaseTypes.items.$RELEASE_ITEM_NAME.releaseName`

Note also that `{{date}}` is not working.

**Comment by flelli** [comment]
Hi @ennioVisco ,

`date` is not a [state](https://mooltiverse.github.io/nyx/guide/user/state-reference/global-attributes/) attribute so `{{date}}` is not supposed to return anything. Where did you get that? Is there any error in the docs?

The issue about the format string should be fixe by using 

```
"releaseName": "{{version}} ({{#timeFormat format=\"20060102\"}} {{timestamp}} {{/timeFormat}})"
```

in place of 

```
"releaseName": "{{version}} ({{#timeFormat format=\"yyyyMMdd\"}} {{timestamp}} {{/timeFormat}})"
```

That's because of the different patterns used by the underlying implementations in Java and Go, as reported in the orange warning box [here](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#timeformat).

Let me know

**Comment by ennioVisco** [comment]
> Hi @ennioVisco ,
> 
> `date` is not a [state](https://mooltiverse.github.io/nyx/guide/user/state-reference/global-attributes/) attribute so `{{date}}` is not supposed to return anything. Where did you get that? Is there any error in the docs?
> 
> The issue about the format string should be fixe by using
> 
> ```
> "releaseName": "{{version}} ({{#timeFormat format=\"20060102\"}} {{timestamp}} {{/timeFormat}})"
> ```
> 
> in place of
> 
> ```
> "releaseName": "{{version}} ({{#timeFormat format=\"yyyyMMdd\"}} {{timestamp}} {{/timeFormat}})"
> ```
> 
> That's because of the different patterns used by the underlying implementations in Java and Go, as reported in the orange warning box [here](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#timeformat).
> 
> Let me know

`{{date}}` is not in the docs, I saw it in the section `{{#releases}}` of the `changelog.hbs` and assumed it would be available.
I can confirm that this solved the issue! Thanks!

**Comment by flelli** [comment]
You're right. That's a [Handlebar built-in](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/templates/#functions) that comes out of the box with Handlebars, but I have no control on that.
