### ISSUE TITLE
Getting a weird version when using gradle on github actions

### ISSUE THREAD

**Issue by bsgrd** [mooltiverse/nyx#294]
When I run my pipeline on github actions with the gradle plugin, I get a version like this:
1.1.0-internal.1+timestamp.20240302175817
That format is not compliant with docker image tags, so my pipeline fails.

When I run nyxInfer locally, I get 1.1.1.

I'm sure i'm doing something wrong, but what? 🤔

I'm using version 2.5.2 and config like this:

```
nyx {
    preset = 'extended'
    changelog {
        path = 'build/CHANGELOG.md'
    }
    releaseTypes {
        publicationServices = ['github']
    }
    services {
        github {
            type = 'GITHUB'
            options {
                AUTHENTICATION_TOKEN = '{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}'
                REPOSITORY_NAME = '//removed'
                REPOSITORY_OWNER = '//removed'
            }
        }
    }
}
```

And github action like this:
```
      - name: Build and test with Gradle
        run: |
          ./gradlew build test \
            -Pmaven_username=${{ secrets.MAVEN_USERNAME }} \
            -Pmaven_password=${{ secrets.MAVEN_PASSWORD }}

      - name: Release version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew nyxClean nyxPublish

      - name: Build and push docker
        run: |
          ./gradlew jib \
            -Pmaven_username=${{ secrets.MAVEN_USERNAME }} \
            -Pmaven_password=${{ secrets.MAVEN_PASSWORD }}
```

**Comment by flelli** [comment]
Hi @bsgrd ,

I'd rather expect the opposite (a clean version when running on GH Actions and a *weird* one locally).
Anyway, that's because in one case (producing the *clean* version) the release type that is matched is the `mainline`, while in the other the `internal` is matched.
Release types are matched by the branch name but also the workspace status or environment variables. By default, the `extended` preset doesn't use environment variables but [expects](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/extended/#release-types) the branch to be in the *clean* state (no uncommitted changes) to match the `mainline`, otherwise, if this condition is not met, it falls back to `internal`.
Do you have uncommitted changes when you run Nyx?

If this doesn't help please check out or send a debug log.

**Comment by bsgrd** [comment]
@flelli you are right. The gradlew script was uncomittet since I changed the permissions in order to execute it 😆
Thank you your help!
