### ISSUE TITLE
Add Java 8 Support

### ISSUE THREAD

**Issue by ConstasJ** [mooltiverse/nyx#310]
Hi. I'm planning to use nyx in my projects. However, as a numerous part of my projects are Minecraft 1.12 mods and plugins, and Java 8 is my only option to build these projects. But nyx seems only support Java 11 and later.
Is it possible to extend backward compatibility to Java 8 and gradle 2.0 (or later gradle versions supporting Java 8)? If not, I'll try to add it on my own fork.
Thank you. Best regards.

**Comment by flelli** [comment]
Hi @ConstasJ ,

we have recently raised the minimum Java version to 17 because maintaining all the dependencies for older versions was becoming overkill.
Moreover, keeping pace with security fixes in dependencies would be impossible because most libraries do not support older Java versions either.
You can still use Nyx < 3.0.0, which is quite stable and doesn't lack any relevant feature, but we are not planning to extend backward compatibility for the above reasons.
