### ISSUE TITLE
[QUESTION] support for appending build metadata to the version output

### ISSUE THREAD

**Issue by fredleger** [mooltiverse/nyx#317]
Hello,

Trying to setup nyx for building an helm chart stored in the rancher catalog format.
For compatibility issue i need the version generated on branches other than main to respect the format `x.y.z+build-meatadata`.
This is totaly semver valid according to https://semver.org/#spec-item-10 but how can i produce such a string using nyx ?
tried with `--bump=my-meta` but it leads to `x.y.z-my-meta.1` which is not supported by rancher (although it's also semver valid)

Thank you for any clue you can have

**Comment by flelli** [comment]
Hi @fredleger ,

the [`--bump`](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#bump) flag indeed doesn't bump the `build` component, which is what you want to bump as far as I understand (since you're using the `+` separator). `--bump` only sets the _major_, _minor_, _patch_ or _pre-release_ components.

What is not clear to me is whether you want to generate a version number based on the Git commit history or by some other values you manage outside of Git. In the first case, just commit your work and let Nyx infer the version number for you, without overriding any value. In the second case Nyx may not be the right tool for you as it's primarily intended to work on the commit history.

Can you give some more details on your use case so I can give you better hints?

**Comment by fredleger** [comment]
Hi @flelli 

sorry re-reading this i realize it wasn't clear enough

- i want to generate based on git history (actually based on other tags already existing in the repo)
- currently nyx is outputing something like detailled bellow
- if i use it straightaway (with `2.31.21-alpha.1`) rancher can't find the new chart
- if i transform it (using some bash) to `2.31.21+alpha.1` it does work

```
nyx infer --verbosity=INFO --summary --bump=alpha
INFO[0001] Version: '2.3.21-alpha.1'                    
branch           = ci/1st-implementation
bump             = alpha
core version     = false
latest version   = false
new release      = false
new version      = true
scheme           = SEMVER
timestamp        = 1718108563576
current version  = 2.3.21-alpha.1
previous version = 2.3.21
prime version    = 2.3.21
```

Found this issue relative to it : https://github.com/rancher/rancher/issues/24863

So i understand there is an in issue in rancher catalog processing since nyx does the job generating semver compatible version numbers but can i work around it in some way with nyx ?

**Comment by flelli** [comment]
Ok , I got it better now,

If you want to just make Rancher happy yes, you can just replace the `+` sign with `-`. This would be syntactically correct, but semantics would be mangled because the _pre-release_ part (after the `-`) is not the same as the _build_ part (after the `+`) from a SemVer perspective. Also consider that a SemVer compliant version might also have both.

From the example you gave I understand you override the bump just to add the _pre-release_ identifier (although you need it to be a _build_ identifier) to a _core_ version number (with just _major_, _minor_ and _patch_). I also see you're not in a `main` branch, so it's reasonable for you to tag with non-core versions.

Long story short, you can configure Nyx by adding a [release type](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/) that [matches your branch](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#match-branches) (`ci/1st-implementation` or anything you need) that creates versions numbers using any [identifier](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#identifiers) you need. Based on the example above you just need to add the identifier with `alpha` as the [qualifier](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#identifier-position) in the `BUILD` [position](https://mooltiverse.github.io/nyx/guide/user/configuration-reference/release-types/#identifier-position).

You can find some examples of release type configurations [here](https://mooltiverse.github.io/nyx/examples/) or you can use a [preset](https://mooltiverse.github.io/nyx/guide/user/configuration-presets/).
